FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src
EXPOSE 80
EXPOSE 443

COPY ["eCommerce.EmailService/eCommerce.EmailService.csproj", "eCommerce.EmailService/"]
COPY ["eCommerce.Model/eCommerce.Model.csproj", "eCommerce.Model/"]
RUN dotnet restore "eCommerce.EmailService/eCommerce.EmailService.csproj"

COPY . .
WORKDIR "/src/eCommerce.EmailService"
RUN dotnet build "eCommerce.EmailService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "eCommerce.EmailService.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "eCommerce.EmailService.dll"]
