version: '3'

services:
  ecommerce-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL__PASSWORD}
      - MSSQL_PID=${SQL__PID}
    ports:
      - "1401:1433"
    expose:
      - 1433
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -C -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - ecommerce-2025

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ__USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ__PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 5672
    networks:
      - ecommerce-2025

  ecommerce-emailservice:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.emailservice
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - ecommerce-sql
      - ecommerce-api
    networks:
      - ecommerce-2025

  ecommerce-api:
    build:
      context: .
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:7093
    ports:
      - "7093:7093"
    networks:
      - ecommerce-2025
    depends_on:
      ecommerce-sql:
        condition: service_healthy
      rabbitmq:
        condition: service_started

networks:
  ecommerce-2025:
    driver: bridge