// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eCommerce.Services.Database;

#nullable disable

namespace eCommerce.Services.Migrations
{
    [DbContext(typeof(IB210033DbContext))]
    partial class IB210033DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eCommerce.Services.Database.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "Mostar"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Name = "Sarajevo"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            Name = "Zenica"
                        });
                });

            modelBuilder.Entity("eCommerce.Services.Database.Connection", b =>
                {
                    b.Property<string>("ConnectionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ConnectionId");

                    b.HasIndex("GroupName");

                    b.ToTable("Connections");
                });

            modelBuilder.Entity("eCommerce.Services.Database.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bosnia and Herzegovina"
                        });
                });

            modelBuilder.Entity("eCommerce.Services.Database.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Barbell"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dumbbell"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pull-up Bar"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Resistance Band"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Treadmill"
                        });
                });

            modelBuilder.Entity("eCommerce.Services.Database.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int?>("ImageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("ImageId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EquipmentId = 1,
                            ImageId = 5,
                            Name = "Bench Press"
                        },
                        new
                        {
                            Id = 2,
                            EquipmentId = 1,
                            ImageId = 8,
                            Name = "Deadlift"
                        },
                        new
                        {
                            Id = 3,
                            EquipmentId = 2,
                            ImageId = 9,
                            Name = "Dumbbell Curl"
                        },
                        new
                        {
                            Id = 4,
                            EquipmentId = 3,
                            ImageId = 4,
                            Name = "Pull-up"
                        },
                        new
                        {
                            Id = 5,
                            EquipmentId = 1,
                            ImageId = 7,
                            Name = "Barbell Squat"
                        },
                        new
                        {
                            Id = 6,
                            EquipmentId = 1,
                            ImageId = 6,
                            Name = "Barbell Row"
                        },
                        new
                        {
                            Id = 7,
                            EquipmentId = 5,
                            ImageId = 10,
                            Name = "Treadmill Run"
                        },
                        new
                        {
                            Id = 8,
                            EquipmentId = 2,
                            ImageId = 11,
                            Name = "Lateral Raise"
                        });
                });

            modelBuilder.Entity("eCommerce.Services.Database.ExerciseMuscleGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("MuscleGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("MuscleGroupId");

                    b.ToTable("ExerciseMuscleGroup");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExerciseId = 1,
                            MuscleGroupId = 1
                        },
                        new
                        {
                            Id = 2,
                            ExerciseId = 1,
                            MuscleGroupId = 3
                        },
                        new
                        {
                            Id = 3,
                            ExerciseId = 2,
                            MuscleGroupId = 2
                        },
                        new
                        {
                            Id = 4,
                            ExerciseId = 2,
                            MuscleGroupId = 4
                        },
                        new
                        {
                            Id = 5,
                            ExerciseId = 3,
                            MuscleGroupId = 5
                        },
                        new
                        {
                            Id = 6,
                            ExerciseId = 4,
                            MuscleGroupId = 2
                        },
                        new
                        {
                            Id = 7,
                            ExerciseId = 5,
                            MuscleGroupId = 4
                        },
                        new
                        {
                            Id = 8,
                            ExerciseId = 6,
                            MuscleGroupId = 2
                        },
                        new
                        {
                            Id = 9,
                            ExerciseId = 7,
                            MuscleGroupId = 4
                        },
                        new
                        {
                            Id = 10,
                            ExerciseId = 8,
                            MuscleGroupId = 3
                        });
                });

            modelBuilder.Entity("eCommerce.Services.Database.ExercisePlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float?>("CustomPrice")
                        .HasColumnType("real");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Reps")
                        .HasColumnType("int");

                    b.Property<int?>("Sets")
                        .HasColumnType("int");

                    b.Property<int>("TrainingPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("TrainingPlanId");

                    b.ToTable("ExercisePlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExerciseId = 1,
                            Note = "Focus on form and controlled movement",
                            Reps = 10,
                            Sets = 3,
                            TrainingPlanId = 1
                        },
                        new
                        {
                            Id = 2,
                            ExerciseId = 5,
                            Note = "Keep back straight, knees tracking over toes",
                            Reps = 12,
                            Sets = 3,
                            TrainingPlanId = 1
                        },
                        new
                        {
                            Id = 3,
                            ExerciseId = 4,
                            Note = "Use assisted machine if full pull-ups are too difficult",
                            Reps = 8,
                            Sets = 3,
                            TrainingPlanId = 1
                        },
                        new
                        {
                            Id = 4,
                            ExerciseId = 2,
                            Note = "Progressive overload - increase weight each week",
                            Reps = 5,
                            Sets = 5,
                            TrainingPlanId = 2
                        },
                        new
                        {
                            Id = 5,
                            ExerciseId = 1,
                            Note = "Drop set on the last set",
                            Reps = 8,
                            Sets = 4,
                            TrainingPlanId = 2
                        },
                        new
                        {
                            Id = 6,
                            Duration = 30,
                            ExerciseId = 7,
                            Note = "Maintain 70-80% of maximum heart rate",
                            TrainingPlanId = 3
                        });
                });

            modelBuilder.Entity("eCommerce.Services.Database.Group", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("eCommerce.Services.Database.GroupTrainingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("KcalBurned")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TrainingType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("GroupTrainingSessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatorId = 1,
                            DurationMinutes = 45,
                            KcalBurned = 450,
                            Name = "Morning Bootcamp",
                            Notes = "Bring a mat and water bottle",
                            Place = "FitLife Gym - Studio A",
                            TrainingType = "Bodyweight Training"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatorId = 1,
                            DurationMinutes = 40,
                            KcalBurned = 350,
                            Name = "Sunset Run",
                            Place = "Central Park Trail",
                            TrainingType = "Running"
                        });
                });

            modelBuilder.Entity("eCommerce.Services.Database.GroupTrainingSessionParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupTrainingSessionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GroupTrainingSessionId", "UserId")
                        .IsUnique();

                    b.ToTable("GroupTrainingSessionParticipants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GroupTrainingSessionId = 1,
                            JoinedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            GroupTrainingSessionId = 2,
                            JoinedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("eCommerce.Services.Database.Gym", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ImageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("ImageId");

                    b.ToTable("Gyms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Titova 15",
                            CityId = 2,
                            Email = "contact@fitlifegym.ba",
                            Name = "FitLife Gym",
                            PhoneNumber = "+387 33 111 111",
                            WorkTime = "Pon-Pet: 06-22h, Sub-Ned: 08-18h"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Bulevar Mira 22",
                            CityId = 1,
                            Email = "info@powerzone.ba",
                            Name = "PowerZone Fitness",
                            PhoneNumber = "+387 36 222 222",
                            WorkTime = "Pon-Ned: 07-23h"
                        });
                });

            modelBuilder.Entity("eCommerce.Services.Database.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsHeader")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsHeader = true,
                            Name = "Ahmet Profile",
                            Size = 204800L,
                            Url = "https://cloudfordiversclub.blob.core.windows.net/takmicenja/users/1/9e3e8fe361ec4270962aea28b798f5e3-Sample_User_Icon.png"
                        },
                        new
                        {
                            Id = 2,
                            IsHeader = true,
                            Name = "Arena1",
                            Size = 204800L,
                            Url = "https://cloudfordiversclub.blob.core.windows.net/takmicenja/general/031c3d0740664e38b58800302259c3ef-arena.jpg"
                        },
                        new
                        {
                            Id = 3,
                            IsHeader = true,
                            Name = "Arena2",
                            Size = 204800L,
                            Url = "https://cloudfordiversclub.blob.core.windows.net/takmicenja/general/498dbeb0028f46f7928417bda2be856d-arena2.png"
                        },
                        new
                        {
                            Id = 4,
                            IsHeader = true,
                            Name = "pull-up",
                            Size = 204800L,
                            Url = "https://cloudfordiversclub.blob.core.windows.net/takmicenja/general/045cfc4432704dff8b23ee0bd602aa09-pull up bar.png"
                        },
                        new
                        {
                            Id = 5,
                            IsHeader = true,
                            Name = "bench-press",
                            Size = 204800L,
                            Url = "https://cloudfordiversclub.blob.core.windows.net/takmicenja/general/b9921a30b8864d3b87b8329883ef4b54-benchh.jpg"
                        },
                        new
                        {
                            Id = 6,
                            IsHeader = true,
                            Name = "row",
                            Size = 204800L,
                            Url = "https://cloudfordiversclub.blob.core.windows.net/takmicenja/general/row.jpeg"
                        },
                        new
                        {
                            Id = 7,
                            IsHeader = true,
                            Name = "squat",
                            Size = 204800L,
                            Url = "https://cloudfordiversclub.blob.core.windows.net/takmicenja/general/squat.jpg"
                        },
                        new
                        {
                            Id = 8,
                            IsHeader = true,
                            Name = "deadlift",
                            Size = 204800L,
                            Url = "https://cloudfordiversclub.blob.core.windows.net/takmicenja/general/deadlift.jpg"
                        },
                        new
                        {
                            Id = 9,
                            IsHeader = true,
                            Name = "curl1",
                            Size = 204800L,
                            Url = "https://cloudfordiversclub.blob.core.windows.net/takmicenja/general/curl1.jpeg"
                        },
                        new
                        {
                            Id = 10,
                            IsHeader = true,
                            Name = "treadmill",
                            Size = 204800L,
                            Url = "https://cloudfordiversclub.blob.core.windows.net/takmicenja/general/treadmill.jpeg"
                        },
                        new
                        {
                            Id = 11,
                            IsHeader = true,
                            Name = "lateral-raise",
                            Size = 204800L,
                            Url = "https://cloudfordiversclub.blob.core.windows.net/takmicenja/general/lateral-raise.jpeg"
                        });
                });

            modelBuilder.Entity("eCommerce.Services.Database.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int");

                    b.Property<int>("PersonalTrainerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientUserId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("PersonalTrainerId");

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("eCommerce.Services.Database.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateRead")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MessageSent")
                        .HasColumnType("datetime2");

                    b.Property<bool>("RecipientDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("RecipientId")
                        .HasColumnType("int");

                    b.Property<bool>("SenderDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("SenderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("eCommerce.Services.Database.MonthlyTrainingStatistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("TrainingSessionCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Year", "Month")
                        .IsUnique();

                    b.ToTable("MonthlyTrainingStatistics");
                });

            modelBuilder.Entity("eCommerce.Services.Database.MuscleGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MuscleGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Chest"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Back"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Shoulders"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Legs"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Arms"
                        });
                });

            modelBuilder.Entity("eCommerce.Services.Database.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("eCommerce.Services.Database.NutritionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Carbs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Fats")
                        .HasColumnType("int");

                    b.Property<int>("PersonalTrainerId")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("Protein")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalCalories")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonalTrainerId");

                    b.HasIndex("UserId");

                    b.ToTable("NutritionPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Carbs = "320g",
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-protein diet plan tailored for muscle building and recovery.",
                            Fats = 80,
                            PersonalTrainerId = 1,
                            Price = 29.99f,
                            Protein = "220g",
                            Title = "Muscle Gain Diet",
                            TotalCalories = "3200",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Carbs = "150g",
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Calorie-deficit diet designed for sustainable and healthy weight loss.",
                            Fats = 60,
                            PersonalTrainerId = 1,
                            Price = 24.99f,
                            Protein = "160g",
                            Title = "Fat Loss Plan",
                            TotalCalories = "1800"
                        },
                        new
                        {
                            Id = 3,
                            Carbs = "380g",
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Carbohydrate-focused plan for endurance athletes and long-distance runners.",
                            Fats = 55,
                            PersonalTrainerId = 2,
                            Price = 19.99f,
                            Protein = "140g",
                            Title = "Endurance Fueling",
                            TotalCalories = "2800"
                        });
                });

            modelBuilder.Entity("eCommerce.Services.Database.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AmountInCents")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripePaymentIntentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountInCents = 4999,
                            CreatedAt = new DateTime(2026, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 1,
                            ItemType = 0,
                            Status = "succeeded",
                            StripePaymentIntentId = "pi_test_3NpL4K2eZvKYlo2C0QJx7aBC",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            AmountInCents = 2999,
                            CreatedAt = new DateTime(2026, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 1,
                            ItemType = 1,
                            Status = "succeeded",
                            StripePaymentIntentId = "pi_test_7MqQ8R5eZvKYlo2C1XPz9eFG",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("eCommerce.Services.Database.PersonalTrainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Certifications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Sport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PersonalTrainers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Certifications = "NASM-CPT, CSCS",
                            Gender = "Male",
                            IsActive = true,
                            Sport = "Karate",
                            UserId = 2,
                            YearsOfExperience = 8
                        },
                        new
                        {
                            Id = 2,
                            Certifications = "ACE-CPT",
                            Gender = "Male",
                            IsActive = true,
                            Sport = "Running",
                            UserId = 3,
                            YearsOfExperience = 3
                        },
                        new
                        {
                            Id = 3,
                            Certifications = "ACE-CC",
                            Gender = "Female",
                            IsActive = true,
                            Sport = "Gym",
                            UserId = 4,
                            YearsOfExperience = 4
                        },
                        new
                        {
                            Id = 4,
                            Certifications = "ACE-DPT",
                            Gender = "Male",
                            IsActive = true,
                            Sport = "Boxing",
                            UserId = 5,
                            YearsOfExperience = 10
                        });
                });

            modelBuilder.Entity("eCommerce.Services.Database.PersonalTrainerRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonalTrainerId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonalTrainerId");

                    b.HasIndex("UserId");

                    b.ToTable("PersonalTrainerRatings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Excellent trainer! Very knowledgeable, motivating, and professional.",
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            PersonalTrainerId = 1,
                            Rating = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Great running coach. Helped me improve my pace and endurance significantly.",
                            CreatedAt = new DateTime(2026, 1, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            PersonalTrainerId = 2,
                            Rating = 4,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("eCommerce.Services.Database.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 17, 11, 39, 25, 533, DateTimeKind.Utc).AddTicks(1439),
                            Description = "Administrator",
                            IsActive = true,
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 17, 11, 39, 25, 533, DateTimeKind.Utc).AddTicks(1440),
                            Description = "Korisnik - kupac",
                            IsActive = true,
                            Name = "Kupac"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 17, 11, 39, 25, 533, DateTimeKind.Utc).AddTicks(1442),
                            Description = "Super Administrator sa svim privilegijama",
                            IsActive = true,
                            Name = "SuperAdmin"
                        });
                });

            modelBuilder.Entity("eCommerce.Services.Database.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonalTrainerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("PersonalTrainerId");

                    b.ToTable("Trainings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 2,
                            Description = "One-on-one session focusing on compound lifts and proper technique.",
                            Duration = 60,
                            Name = "Strength Foundation",
                            PersonalTrainerId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Treadmill intervals and circuit training session for fat burn.",
                            Duration = 45,
                            Name = "Cardio Conditioning",
                            PersonalTrainerId = 2
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 2,
                            Description = "Guided stretching, foam rolling, and mobility work.",
                            Duration = 30,
                            Name = "Mobility & Recovery",
                            PersonalTrainerId = 1
                        });
                });

            modelBuilder.Entity("eCommerce.Services.Database.TrainingPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("BasePrice")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonalTrainerId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonalTrainerId");

                    b.HasIndex("UserId");

                    b.ToTable("TrainingPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 49.99f,
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A 4-week program for building foundational strength using compound lifts.",
                            PersonalTrainerId = 1,
                            Title = "Beginner Strength Program",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 79.99f,
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "12-week muscle-building program designed for experienced lifters.",
                            PersonalTrainerId = 1,
                            Title = "Advanced Hypertrophy",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 39.99f,
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-intensity cardio program focused on fat loss and endurance.",
                            PersonalTrainerId = 2,
                            Title = "Cardio Blast"
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 59.99f,
                            CreatedAt = new DateTime(2026, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Focused upper body strength and hypertrophy plan for intermediate clients.",
                            PersonalTrainerId = 3,
                            Title = "Upper Body Builder"
                        },
                        new
                        {
                            Id = 5,
                            BasePrice = 69.99f,
                            CreatedAt = new DateTime(2026, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Conditioning plan for boxing stamina, core stability, and footwork.",
                            PersonalTrainerId = 4,
                            Title = "Boxing Conditioning"
                        });
                });

            modelBuilder.Entity("eCommerce.Services.Database.TrainingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CancelledByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("GymId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonalTrainerId")
                        .HasColumnType("int");

                    b.Property<float?>("Price")
                        .HasColumnType("real");

                    b.Property<DateTime>("ScheduledDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TrainerNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("GymId");

                    b.HasIndex("PersonalTrainerId");

                    b.ToTable("TrainingSessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 2,
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationMinutes = 60,
                            GymId = 1,
                            Notes = "Please bring lifting gloves",
                            PersonalTrainerId = 1,
                            Price = 50f,
                            ScheduledDateTime = new DateTime(2026, 3, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            TrainerNotes = "Client needs focus on squat depth"
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 2,
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationMinutes = 60,
                            GymId = 1,
                            PersonalTrainerId = 1,
                            Price = 50f,
                            ScheduledDateTime = new DateTime(2026, 3, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationMinutes = 45,
                            GymId = 2,
                            Notes = "Open availability slot",
                            PersonalTrainerId = 2,
                            Price = 40f,
                            ScheduledDateTime = new DateTime(2026, 3, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0
                        });
                });

            modelBuilder.Entity("eCommerce.Services.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BanExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("BanReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ProfileImageId")
                        .HasColumnType("int");

                    b.Property<string>("ResetCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime?>("ResetCodeExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ProfileImageId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 17, 11, 39, 25, 533, DateTimeKind.Utc).AddTicks(1688),
                            Email = "ahmet.stupac@edu.fit.ba",
                            FirstName = "Ahmet",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Stupac",
                            PasswordHash = "cnmepYg0B3XVzwr9POBGEWwEAzNGv+KuqebPm0/AvFk=",
                            PasswordSalt = "Qeunp0McejKht6Qx9PW6ug==",
                            ProfileImageId = 1,
                            Username = "superadmin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 17, 11, 39, 25, 533, DateTimeKind.Utc).AddTicks(1692),
                            Email = "adil@edu.fit.ba",
                            FirstName = "Denis",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Music",
                            PasswordHash = "cnmepYg0B3XVzwr9POBGEWwEAzNGv+KuqebPm0/AvFk=",
                            PasswordSalt = "Qeunp0McejKht6Qx9PW6ug==",
                            ProfileImageId = 1,
                            Username = "desktop"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 17, 11, 39, 25, 533, DateTimeKind.Utc).AddTicks(1694),
                            Email = "ahmet2.stupac@edu.fit.ba",
                            FirstName = "Ismail",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Catic",
                            PasswordHash = "cnmepYg0B3XVzwr9POBGEWwEAzNGv+KuqebPm0/AvFk=",
                            PasswordSalt = "Qeunp0McejKht6Qx9PW6ug==",
                            ProfileImageId = 1,
                            Username = "trener2"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 5, 17, 11, 39, 25, 533, DateTimeKind.Utc).AddTicks(1696),
                            Email = "ahmet3.stupac@edu.fit.ba",
                            FirstName = "Alem",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Stupac",
                            PasswordHash = "cnmepYg0B3XVzwr9POBGEWwEAzNGv+KuqebPm0/AvFk=",
                            PasswordSalt = "Qeunp0McejKht6Qx9PW6ug==",
                            ProfileImageId = 1,
                            Username = "trener3"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 5, 17, 11, 39, 25, 533, DateTimeKind.Utc).AddTicks(1698),
                            Email = "ahmet4.stupac@edu.fit.ba",
                            FirstName = "Adil",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Joldic",
                            PasswordHash = "cnmepYg0B3XVzwr9POBGEWwEAzNGv+KuqebPm0/AvFk=",
                            PasswordSalt = "Qeunp0McejKht6Qx9PW6ug==",
                            ProfileImageId = 1,
                            Username = "trener4"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 5, 17, 11, 39, 25, 533, DateTimeKind.Utc).AddTicks(1701),
                            Email = "ahmet5.stupac@edu.fit.ba",
                            FirstName = "Amel",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Music",
                            PasswordHash = "cnmepYg0B3XVzwr9POBGEWwEAzNGv+KuqebPm0/AvFk=",
                            PasswordSalt = "Qeunp0McejKht6Qx9PW6ug==",
                            ProfileImageId = 1,
                            Username = "trener5"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 5, 17, 11, 39, 25, 533, DateTimeKind.Utc).AddTicks(1703),
                            Email = "ahmet6.stupac@edu.fit.ba",
                            FirstName = "Emina",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Junuz",
                            PasswordHash = "cnmepYg0B3XVzwr9POBGEWwEAzNGv+KuqebPm0/AvFk=",
                            PasswordSalt = "Qeunp0McejKht6Qx9PW6ug==",
                            ProfileImageId = 1,
                            Username = "mobile"
                        });
                });

            modelBuilder.Entity("eCommerce.Services.Database.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAssigned")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAssigned = new DateTime(2026, 5, 17, 11, 39, 25, 533, DateTimeKind.Utc).AddTicks(1731),
                            RoleId = 3,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateAssigned = new DateTime(2026, 5, 17, 11, 39, 25, 533, DateTimeKind.Utc).AddTicks(1732),
                            RoleId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            DateAssigned = new DateTime(2026, 5, 17, 11, 39, 25, 533, DateTimeKind.Utc).AddTicks(1733),
                            RoleId = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 5,
                            DateAssigned = new DateTime(2026, 5, 17, 11, 39, 25, 533, DateTimeKind.Utc).AddTicks(1740),
                            RoleId = 1,
                            UserId = 4
                        },
                        new
                        {
                            Id = 6,
                            DateAssigned = new DateTime(2026, 5, 17, 11, 39, 25, 533, DateTimeKind.Utc).AddTicks(1741),
                            RoleId = 1,
                            UserId = 5
                        },
                        new
                        {
                            Id = 7,
                            DateAssigned = new DateTime(2026, 5, 17, 11, 39, 25, 533, DateTimeKind.Utc).AddTicks(1742),
                            RoleId = 1,
                            UserId = 6
                        },
                        new
                        {
                            Id = 8,
                            DateAssigned = new DateTime(2026, 5, 17, 11, 39, 25, 533, DateTimeKind.Utc).AddTicks(1744),
                            RoleId = 2,
                            UserId = 7
                        });
                });

            modelBuilder.Entity("eCommerce.Services.Database.City", b =>
                {
                    b.HasOne("eCommerce.Services.Database.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("eCommerce.Services.Database.Connection", b =>
                {
                    b.HasOne("eCommerce.Services.Database.Group", "Group")
                        .WithMany("Connections")
                        .HasForeignKey("GroupName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("eCommerce.Services.Database.Exercise", b =>
                {
                    b.HasOne("eCommerce.Services.Database.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eCommerce.Services.Database.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.Navigation("Equipment");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("eCommerce.Services.Database.ExerciseMuscleGroup", b =>
                {
                    b.HasOne("eCommerce.Services.Database.Exercise", "Exercise")
                        .WithMany("ExerciseMuscleGroups")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eCommerce.Services.Database.MuscleGroup", "MuscleGroup")
                        .WithMany()
                        .HasForeignKey("MuscleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("MuscleGroup");
                });

            modelBuilder.Entity("eCommerce.Services.Database.ExercisePlan", b =>
                {
                    b.HasOne("eCommerce.Services.Database.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eCommerce.Services.Database.TrainingPlan", "TrainingPlan")
                        .WithMany("ExercisePlans")
                        .HasForeignKey("TrainingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("TrainingPlan");
                });

            modelBuilder.Entity("eCommerce.Services.Database.GroupTrainingSession", b =>
                {
                    b.HasOne("eCommerce.Services.Database.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("eCommerce.Services.Database.GroupTrainingSessionParticipant", b =>
                {
                    b.HasOne("eCommerce.Services.Database.GroupTrainingSession", "GroupTrainingSession")
                        .WithMany("Participants")
                        .HasForeignKey("GroupTrainingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eCommerce.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GroupTrainingSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eCommerce.Services.Database.Gym", b =>
                {
                    b.HasOne("eCommerce.Services.Database.City", "City")
                        .WithMany("Gyms")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("eCommerce.Services.Database.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.Navigation("City");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("eCommerce.Services.Database.Image", b =>
                {
                    b.HasOne("eCommerce.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eCommerce.Services.Database.Membership", b =>
                {
                    b.HasOne("eCommerce.Services.Database.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eCommerce.Services.Database.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("eCommerce.Services.Database.PersonalTrainer", "PersonalTrainer")
                        .WithMany()
                        .HasForeignKey("PersonalTrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Payment");

                    b.Navigation("PersonalTrainer");
                });

            modelBuilder.Entity("eCommerce.Services.Database.Message", b =>
                {
                    b.HasOne("eCommerce.Services.Database.User", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("eCommerce.Services.Database.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("eCommerce.Services.Database.MonthlyTrainingStatistics", b =>
                {
                    b.HasOne("eCommerce.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("eCommerce.Services.Database.Notification", b =>
                {
                    b.HasOne("eCommerce.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("eCommerce.Services.Database.NutritionPlan", b =>
                {
                    b.HasOne("eCommerce.Services.Database.PersonalTrainer", "PersonalTrainer")
                        .WithMany()
                        .HasForeignKey("PersonalTrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eCommerce.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("PersonalTrainer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eCommerce.Services.Database.Payment", b =>
                {
                    b.HasOne("eCommerce.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("eCommerce.Services.Database.PersonalTrainer", b =>
                {
                    b.HasOne("eCommerce.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("eCommerce.Services.Database.PersonalTrainerRating", b =>
                {
                    b.HasOne("eCommerce.Services.Database.PersonalTrainer", "PersonalTrainer")
                        .WithMany("Ratings")
                        .HasForeignKey("PersonalTrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eCommerce.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonalTrainer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eCommerce.Services.Database.Training", b =>
                {
                    b.HasOne("eCommerce.Services.Database.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("eCommerce.Services.Database.PersonalTrainer", "PersonalTrainer")
                        .WithMany()
                        .HasForeignKey("PersonalTrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("PersonalTrainer");
                });

            modelBuilder.Entity("eCommerce.Services.Database.TrainingPlan", b =>
                {
                    b.HasOne("eCommerce.Services.Database.PersonalTrainer", "PersonalTrainer")
                        .WithMany()
                        .HasForeignKey("PersonalTrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eCommerce.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("PersonalTrainer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eCommerce.Services.Database.TrainingSession", b =>
                {
                    b.HasOne("eCommerce.Services.Database.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("eCommerce.Services.Database.Gym", "Gym")
                        .WithMany()
                        .HasForeignKey("GymId");

                    b.HasOne("eCommerce.Services.Database.PersonalTrainer", "PersonalTrainer")
                        .WithMany()
                        .HasForeignKey("PersonalTrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Gym");

                    b.Navigation("PersonalTrainer");
                });

            modelBuilder.Entity("eCommerce.Services.Database.User", b =>
                {
                    b.HasOne("eCommerce.Services.Database.Image", "ProfileImage")
                        .WithMany()
                        .HasForeignKey("ProfileImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ProfileImage");
                });

            modelBuilder.Entity("eCommerce.Services.Database.UserRole", b =>
                {
                    b.HasOne("eCommerce.Services.Database.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eCommerce.Services.Database.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eCommerce.Services.Database.City", b =>
                {
                    b.Navigation("Gyms");
                });

            modelBuilder.Entity("eCommerce.Services.Database.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("eCommerce.Services.Database.Exercise", b =>
                {
                    b.Navigation("ExerciseMuscleGroups");
                });

            modelBuilder.Entity("eCommerce.Services.Database.Group", b =>
                {
                    b.Navigation("Connections");
                });

            modelBuilder.Entity("eCommerce.Services.Database.GroupTrainingSession", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("eCommerce.Services.Database.PersonalTrainer", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("eCommerce.Services.Database.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("eCommerce.Services.Database.TrainingPlan", b =>
                {
                    b.Navigation("ExercisePlans");
                });

            modelBuilder.Entity("eCommerce.Services.Database.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
